apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: demo-app:/Service:demo-namespace/frontend
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"demo-app:/Service:demo-namespace/frontend"},"name":"frontend","namespace":"demo-namespace"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"frontend"},"type":"ClusterIP"}}
  creationTimestamp: "2026-06-21T18:27:05Z"
  name: frontend
  namespace: demo-namespace
  resourceVersion: "489596"
  uid: 344286fb-0d3b-4806-8d22-74bfa51b847d
spec:
  clusterIP: 10.43.118.213
  clusterIPs:
  - 10.43.118.213
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
