apiVersion: v1
kind: Service
metadata:
  name: mardan-backend
  namespace: demo-namespace
spec:
  selector:
    app: auth-service
  ports:
  - port: 5000       # nginx yahan connect karta hai
    targetPort: 5001  # auth-service pod yahan sunta hai
