apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: mardan-smart-city
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/metrics"
    prometheus.io/port: "5003"
spec:
  selector:
    app: notification-service
  ports:
  - port: 5003
    targetPort: 5003
