apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-redis-auth
  namespace: demo-namespace
spec:
  secretTargetRef:
  - parameter: password
    name: keda-redis-secret
    key: redis_password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: complaint-service-scaler
  namespace: demo-namespace
spec:
  scaleTargetRef:
    name: complaint-service
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: redis
    authenticationRef:
      name: keda-redis-auth
    metadata:
      address: redis.demo-namespace.svc.cluster.local:6379
      listName: bull:notifications:wait
      listLength: "5"
