apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config/backend-config.yaml
  - config/postgres-init-configmap.yaml
  - secrets/backend-sealed-secret.yaml
  - secrets/postgres-sealed-secret.yaml
  - secrets/grafana-sealed-secret.yaml
  - storage/redis-pvc.yaml
  - storage/uploads-pvc.yaml
  - storage/grafana-pvc.yaml
  - storage/prometheus-pvc.yaml
  - security/service-accounts.yaml
  - security/roles.yaml
  - security/role-bindings.yaml
  - security/gatekeeper-constraints.yaml
  - policies/default-deny.yaml
  - policies/linkerd-access.yaml
  - policies/backend-access.yaml
  - policies/redis-access.yaml
  - policies/db-access.yaml
  - policies/monitoring-access.yaml
  - deployments/postgres-deployment.yaml
  - deployments/pgbouncer-userlist-configmap.yaml
  - deployments/pgbouncer-deployment.yaml
  - deployments/redis-deployment.yaml
  - deployments/auth-deployment.yaml
  - deployments/complaint-deployment.yaml
  - deployments/notification-deployment.yaml
  - deployments/frontend-deployment.yaml
  - services/postgres-service.yaml
  - services/redis-service.yaml
  - services/mardan-backend-service.yaml
  - services/auth-service.yaml
  - services/complaint-service.yaml
  - services/notification-service.yaml
  - services/frontend-service.yaml
  - services/pgbouncer-service.yaml
  - ingress/main-ingress.yaml
  - autoscaling/backend-hpa.yaml
  - autoscaling/frontend-hpa.yaml
  - reliability/backend-pdb.yaml
  - reliability/frontend-pdb.yaml
  - reliability/postgres-backup-cronjob.yaml
  - storage/loki-pvc.yaml
  - storage/tempo-pvc.yaml
  - observability/loki-config.yaml
  - observability/loki-deployment.yaml
  - observability/fluent-bit.yaml
  - observability/tempo-config.yaml
  - observability/tempo-deployment.yaml
  - observability/grafana-deployment.yaml
  - observability/prometheus-deployment.yaml
  - observability/node-exporter.yaml
  - observability/node-exporter-namespace.yaml
  - gitops/argocd-app.yaml
  - gitops/argocd-project.yaml
  - autoscaling/complaint-keda-scaler.yaml
  - autoscaling/keda-redis-secret.yaml
  - middleware/middleware-ratelimit.yaml
  - security/allowed-registry.yaml
  - security/allowed-registry-constraint.yaml
  - security/rbac-per-service.yaml
