apiVersion: v1
kind: Namespace
metadata:
  name: demo-namespace
  labels:
    kubernetes.io/metadata.name: demo-namespace
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
