apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: demo-namespace
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      http_listen_address: 0.0.0.0
    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m
    compactor:
      compaction:
        block_retention: 48h
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        wal:
          path: /tmp/tempo/wal
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
