apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: node-exporter-access
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: node-exporter
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: demo-namespace
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 9100
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-egress
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: demo-namespace
      podSelector:
        matchLabels:
          app: auth-service
    ports:
    - protocol: TCP
      port: 5001
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: demo-namespace
      podSelector:
        matchLabels:
          app: complaint-service
    ports:
    - protocol: TCP
      port: 5002
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: demo-namespace
      podSelector:
        matchLabels:
          app: notification-service
    ports:
    - protocol: TCP
      port: 5003
  - to:
    - podSelector:
        matchLabels:
          app: node-exporter
    ports:
    - protocol: TCP
      port: 9100
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tempo-access
  namespace: demo-namespace
spec:
  podSelector:
    matchLabels:
      app: tempo
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: grafana
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-access
  namespace: demo-namespace
spec:
  podSelector:
    matchLabels:
      app: loki
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: grafana
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana-prometheus-access
  namespace: demo-namespace
spec:
  podSelector:
    matchLabels:
      app: grafana
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - port: 9090
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: loki
    ports:
    - port: 3100
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: tempo
    ports:
    - port: 3200
      protocol: TCP
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-egress-demo
  namespace: demo-namespace
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: auth-service
    ports:
    - protocol: TCP
      port: 5001
  - to:
    - podSelector:
        matchLabels:
          app: complaint-service
    ports:
    - protocol: TCP
      port: 5002
  - to:
    - podSelector:
        matchLabels:
          app: notification-service
    ports:
    - protocol: TCP
      port: 5003
  - to:
    - ipBlock:
        cidr: 192.168.100.249/32
    ports:
    - protocol: TCP
      port: 9100
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
