apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: demo-namespace
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: demo-namespace
automountServiceAccountToken: false
