apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mardan-project
  namespace: argocd
spec:
  description: Mardan Smart City Project
  sourceRepos:
  - 'https://github.com/shoaibikhan-dev/mardan-smart.git'
  destinations:
  - namespace: mardan-smart-city
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
