apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mardan-smart-city
  namespace: argocd
spec:
  project: mardan-project
  source:
    repoURL: 'https://github.com/shoaibikhan-dev/demo_1.git'
    targetRevision: HEAD
    path: k3s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
