---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: demo-namespace
spec:
  encryptedData:
    admin-password: AgAe1/xLGiTIS3QwwvdtS4qv9NJNo3te4Qaa56nhg3W6NG4beXK8zerxQp88fSnOaa8OQ+s0XbuFTJ2KmfgcboeWt3Aow3RnE3eP8PrpwJ7pgjNCmuOhhnch+KR7lTDe2LWahSHPljiSqHmoofTalX3i/tqF3ZW4d3pS68CDNQfcHrgMfp9PWdTAHlka9diKFD2312SajvidIdGEMSSdc6AbJfbgrT/Xn3X9x2WGmhTr05nnq2FtBe8puXPtCLed8he1baYS6S/YrdrFno+6fgc6eCGoMnNcVNMo1iX6ZCA/RYruNiLoImafRyruxpY8C5phzpSKCN4HVBePg4cy5fzR1Pb8xVpCO5mXTes08z+p9XpWuh9tBudskMpSaoVFEkRFWwBf8y3YugA7yvlY+iun4m35eJgWjI9YRKW+z8YxoPRTYry3ivsFlf8/AZw7KxNEBZeR47lrIahMa+7tzU6kKaqqJG19UmtH9bZMYlyqttp+BAWtARxaJqbr5FBsHlS6A7hoTi0Socm6sOPJYJeqCNLQsRGgd7B8xFJWb7mau3O2pllJjle1b57uQ+7B1QJMUeAIQYISzOGf7iQxDrGuhudHirh1giLkxLPDcCg6Bf5Oh/+dUrZyAY6Iz314fzziq+Nl0Vf1Qs4HQllq/zK37gRy1bl2AvhSFs3twtpmMw9txS2WSz4YmbM223XUYAjDC7DzUAjWxqNCThdXYjw6Dm0F37kV
  template:
    metadata:
      name: grafana-secret
      namespace: demo-namespace
    type: Opaque
